name: Build FluffOS for ARM64 on Armbian

on:
  workflow_dispatch:  # 添加手动触发选项
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git cmake qemu-user-static binfmt-support \
          g++-aarch64-linux-gnu libevent-dev

    - name: Set up QEMU
      run: |
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - name: Build for ARM64
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++ ..
        make -j$(nproc)

    - name: Archive the build
      uses: actions/upload-artifact@v3
      with:
        name: fluffos-arm64
        path: build/bin/
